# Generated by Django 5.2.15 on 2026-06-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='estimated_hours',
        ),
        migrations.RemoveField(
            model_name='task',
            name='progress',
        ),
    ]
